[package]
name = "mleap-rust"
version = "0.1.0"
authors = ["christophermcandrews"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix = "0.22.0"
rust-blas = "0.1.3"
